roll back

diff --git a/build.jenkinsfile b/build.jenkinsfile
--- a/build.jenkinsfile
+++ b/build.jenkinsfile
@@ -4,22 +4,24 @@ pipeline {
     environment {
         PYTHON_IMG_NAME = "python-app:${BUILD_NUMBER}"
         NGINX_IMG_NAME = "nginx-static:${BUILD_NUMBER}"
-        SNYK_TOKEN = credentials('snyk-token')
-        NEXUS_BASE_URL = 'http://localhost:8081'
-        NEXUS_REPOSITORY_PATH = 'repository/ben-nexus'
-        DOCKER_CREDENTIALS_ID = 'nexus-credentials-id'
+        SNYK_TOKEN = credentials('snyk-token') // Ensure you have a Jenkins credential with ID 'snyk-token'
     }
 
     stages {
-        stage('Build and Push to Docker Hub') {
+        stage('Build Docker Images') {
             steps {
                 withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'USERNAME', passwordVariable: 'USERPASS')]) {
                     script {
+                        // Build and push Python app image
                         sh '''
                             echo "$USERPASS" | docker login -u "$USERNAME" --password-stdin
                             docker build -t "$PYTHON_IMG_NAME" -f Dockerfile.python .
                             docker tag "$PYTHON_IMG_NAME" exaclly/"$PYTHON_IMG_NAME"
                             docker push exaclly/"$PYTHON_IMG_NAME"
+                        '''
+                        // Build and push Nginx image
+                        sh '''
+                            echo "$USERPASS" | docker login -u "$USERNAME" --password-stdin
                             docker build -t "$NGINX_IMG_NAME" -f Dockerfile.nginx .
                             docker tag "$NGINX_IMG_NAME" exaclly/"$NGINX_IMG_NAME"
                             docker push exaclly/"$NGINX_IMG_NAME"
@@ -29,76 +31,22 @@ pipeline {
             }
         }
 
-        stage('Build and Push to Nexus') {
-            steps {
-                withCredentials([usernamePassword(credentialsId: DOCKER_CREDENTIALS_ID, usernameVariable: 'USERNAME', passwordVariable: 'USERPASS')]) {
-                    script {
-                        sh '''
-                            echo "$USERPASS" | docker login $NEXUS_BASE_URL -u "$USERNAME" --password-stdin
-                            docker build -t "$NEXUS_BASE_URL/$NEXUS_REPOSITORY_PATH/$PYTHON_IMG_NAME" -f Dockerfile.python .
-                            docker push "$NEXUS_BASE_URL/$NEXUS_REPOSITORY_PATH/$PYTHON_IMG_NAME"
-                            docker build -t "$NEXUS_BASE_URL/$NEXUS_REPOSITORY_PATH/$NGINX_IMG_NAME" -f Dockerfile.nginx .
-                            docker push "$NEXUS_BASE_URL/$NEXUS_REPOSITORY_PATH/$NGINX_IMG_NAME"
-                        '''
-                    }
-                }
-            }
-        }
-
-        stage('Verify Push to Nexus') {
-            steps {
-                script {
-                    def pythonImageExists = sh(script: "curl -s -o /dev/null -w '%{http_code}' -u $USERNAME:$USERPASS $NEXUS_BASE_URL/$NEXUS_REPOSITORY_PATH/v2/python-app/manifests/${BUILD_NUMBER}", returnStatus: true)
-                    def nginxImageExists = sh(script: "curl -s -o /dev/null -w '%{http_code}' -u $USERNAME:$USERPASS $NEXUS_BASE_URL/$NEXUS_REPOSITORY_PATH/v2/nginx-static/manifests/${BUILD_NUMBER}", returnStatus: true)
-
-                    if (pythonImageExists != 200 || nginxImageExists != 200) {
-                        error("One or more images failed to push to Nexus")
-                    } else {
-                        echo "Images pushed to Nexus successfully"
-                    }
-                }
-            }
-        }
-
         stage('Install Dependencies') {
             steps {
-                sh 'pip3 install -r requirements.txt'
+                sh 'pip3 install pytest unittest2'
             }
         }
 
-        stage('Static Analysis and Tests') {
-            parallel {
-                stage('Static Code Linting') {
-                    steps {
-                        script {
-                            def pylintStatus = sh(script: 'python3 -m pylint -f parseable --reports=no *.py > pylint.log', returnStatus: true)
-                            if (pylintStatus != 0) {
-                                currentBuild.result = 'UNSTABLE'
-                            }
-                        }
-                    }
-                    post {
-                        always {
-                            sh 'cat pylint.log'
-                            recordIssues (
-                                enabledForFailure: true,
-                                aggregatingResults: true,
-                                tools: [pyLint(name: 'Pylint', pattern: '**/pylint.log')]
-                            )
-                        }
-                    }
+        stage('Unittest') {
+            steps {
+                script {
+                    // Run unit tests
+                    sh 'python3 -m pytest --junitxml results.xml tests/test_demo.py'
                 }
-                stage('Unittest') {
-                    steps {
-                        script {
-                            sh 'python3 -m pytest --junitxml results.xml tests/'
-                        }
-                    }
-                    post {
-                        always {
-                            junit allowEmptyResults: true, testResults: 'results.xml'
-                        }
-                    }
+            }
+            post {
+                always {
+                    junit allowEmptyResults: true, testResults: 'results.xml'
                 }
             }
         }
@@ -157,28 +105,34 @@ pipeline {
     post {
         always {
             script {
+                // Log the start of the cleanup process
                 echo 'Starting cleanup process...'
+
+                // Remove the built Docker images from the disk
                 try {
                     sh '''
-                        echo "Removing Docker image: exaclly/${PYTHON_IMG_NAME}"
-                        docker rmi exaclly/${PYTHON_IMG_NAME} || echo "Image exaclly/${PYTHON_IMG_NAME} already removed or not found."
+                        echo "Removing Docker image: exaclly/$PYTHON_IMG_NAME"
+                        docker rmi exaclly/$PYTHON_IMG_NAME || echo "Image exaclly/$PYTHON_IMG_NAME already removed or not found."
                     '''
                 } catch (Exception e) {
-                    echo "Error during Docker image removal of ${PYTHON_IMG_NAME}: ${e}"
+                    echo "Error during Docker image removal: ${e.getMessage()}"
                 }
+
                 try {
                     sh '''
-                        echo "Removing Docker image: exaclly/${NGINX_IMG_NAME}"
-                        docker rmi exaclly/${NGINX_IMG_NAME} || echo "Image exaclly/${NGINX_IMG_NAME} already removed or not found."
+                        echo "Removing Docker image: exaclly/$NGINX_IMG_NAME"
+                        docker rmi exaclly/$NGINX_IMG_NAME || echo "Image exaclly/$NGINX_IMG_NAME already removed or not found."
                     '''
                 } catch (Exception e) {
-                    echo "Error during Docker image removal of ${NGINX_IMG_NAME}: ${e}"
+                    echo "Error during Docker image removal: ${e.getMessage()}"
                 }
+
+                // Clean the workspace
                 cleanWs()
+
+                // Log the end of the cleanup process
                 echo 'Cleanup process completed.'
             }
         }
     }
 }
-
-echo "plz"
