test

diff --git a/build.jenkinsfile b/build.jenkinsfile
--- a/build.jenkinsfile
+++ b/build.jenkinsfile
@@ -1,27 +1,25 @@
 pipeline {
     agent any
-
     environment {
         PYTHON_IMG_NAME = "python-app:${BUILD_NUMBER}"
         NGINX_IMG_NAME = "nginx-static:${BUILD_NUMBER}"
-        SNYK_TOKEN = credentials('snyk-token') // Ensure you have a Jenkins credential with ID 'snyk-token'
+        SNYK_TOKEN = credentials('snyk-token')
+        NEXUS_REPOSITORY_URL = 'http://localhost:8081/repository/ben-nexus'
+        NEXUS_BASE_URL = 'http://localhost:8081'
+        NEXUS_REPOSITORY_PATH = 'repository/ben-nexus'
+        DOCKER_CREDENTIALS_ID = 'nexus-credentials-id'
     }
 
     stages {
-        stage('Build Docker Images') {
+        stage('Build and Push to Docker Hub') {
             steps {
                 withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'USERNAME', passwordVariable: 'USERPASS')]) {
                     script {
-                        // Build and push Python app image
                         sh '''
                             echo "$USERPASS" | docker login -u "$USERNAME" --password-stdin
                             docker build -t "$PYTHON_IMG_NAME" -f Dockerfile.python .
                             docker tag "$PYTHON_IMG_NAME" exaclly/"$PYTHON_IMG_NAME"
                             docker push exaclly/"$PYTHON_IMG_NAME"
-                        '''
-                        // Build and push Nginx image
-                        sh '''
-                            echo "$USERPASS" | docker login -u "$USERNAME" --password-stdin
                             docker build -t "$NGINX_IMG_NAME" -f Dockerfile.nginx .
                             docker tag "$NGINX_IMG_NAME" exaclly/"$NGINX_IMG_NAME"
                             docker push exaclly/"$NGINX_IMG_NAME"
@@ -30,27 +28,83 @@ pipeline {
                 }
             }
         }
-
-        stage('Install Dependencies') {
+        stage('Build and Push to Nexus') {
             steps {
-                sh 'pip3 install pytest unittest2'
+                withCredentials([usernamePassword(credentialsId: DOCKER_CREDENTIALS_ID, usernameVariable: 'USERNAME', passwordVariable: 'USERPASS')]) {
+                    script {
+                        sh '''
+                            echo "$USERPASS" | docker login $NEXUS_REPOSITORY_URL -u "$USERNAME" --password-stdin
+                            docker build -t "$NEXUS_REPOSITORY_URL/python-app:${BUILD_NUMBER}" -f Dockerfile.python .
+                            docker push "$NEXUS_REPOSITORY_URL/python-app:${BUILD_NUMBER}"
+                            docker build -t "$NEXUS_REPOSITORY_URL/nginx-static:${BUILD_NUMBER}" -f Dockerfile.nginx .
+                            docker push "$NEXUS_REPOSITORY_URL/nginx-static:${BUILD_NUMBER}"
+                            echo "$USERPASS" | docker login $NEXUS_BASE_URL -u "$USERNAME" --password-stdin
+                            docker build -t "$NEXUS_BASE_URL/$NEXUS_REPOSITORY_PATH/$PYTHON_IMG_NAME" -f Dockerfile.python .
+                            docker push "$NEXUS_BASE_URL/$NEXUS_REPOSITORY_PATH/$PYTHON_IMG_NAME"
+                            docker build -t "$NEXUS_BASE_URL/$NEXUS_REPOSITORY_PATH/$NGINX_IMG_NAME" -f Dockerfile.nginx .
+                            docker push "$NEXUS_BASE_URL/$NEXUS_REPOSITORY_PATH/$NGINX_IMG_NAME"
+                        '''
+                    }
+                }
             }
         }
-
-        stage('Unittest') {
+        stage('Verify Push to Nexus') {
             steps {
                 script {
-                    // Run unit tests
-                    sh 'python3 -m pytest --junitxml results.xml tests/test_demo.py'
-                }
-            }
-            post {
-                always {
-                    junit allowEmptyResults: true, testResults: 'results.xml'
+                    def pythonImageExists = sh(script: "curl -s -o /dev/null -w '%{http_code}' -u $USERNAME:$USERPASS $NEXUS_REPOSITORY_URL/v2/python-app/manifests/${BUILD_NUMBER}", returnStatus: true)
+                    def nginxImageExists = sh(script: "curl -s -o /dev/null -w '%{http_code}' -u $USERNAME:$USERPASS $NEXUS_REPOSITORY_URL/v2/nginx-static/manifests/${BUILD_NUMBER}", returnStatus: true)
+                    def pythonImageExists = sh(script: "curl -s -o /dev/null -w '%{http_code}' -u $USERNAME:$USERPASS $NEXUS_BASE_URL/$NEXUS_REPOSITORY_PATH/v2/python-app/manifests/${BUILD_NUMBER}", returnStatus: true)
+                    def nginxImageExists = sh(script: "curl -s -o /dev/null -w '%{http_code}' -u $USERNAME:$USERPASS $NEXUS_BASE_URL/$NEXUS_REPOSITORY_PATH/v2/nginx-static/manifests/${BUILD_NUMBER}", returnStatus: true)
+
+                    if (pythonImageExists != 200 || nginxImageExists != 200) {
+                        error("One or more images failed to push to Nexus")
+                    } else {
+                        echo "Images pushed to Nexus successfully"
+                    }
                 }
             }
         }
-
+        stage('Install Dependencies') {
+            steps {
+                sh 'pip3 install -r requirements.txt'
+            }
+        }
+        stage('Static Analysis and Tests') {
+            parallel {
+                stage('Static Code Linting') {
+                    steps {
+                        script {
+                            def pylintStatus = sh(script: 'python3 -m pylint -f parseable --reports=no *.py > pylint.log', returnStatus: true)
+                            if (pylintStatus != 0) {
+                                currentBuild.result = 'UNSTABLE'
+                            }
+                        }
+                    }
+                    post {
+                        always {
+                            sh 'cat pylint.log'
+                            recordIssues (
+                                enabledForFailure: true,
+                                aggregatingResults: true,
+                                tools: [pyLint(name: 'Pylint', pattern: '**/pylint.log')]
+                            )
+                        }
+                    }
+                }
+                stage('Unittest') {
+                    steps {
+                        script {
+                            sh 'python3 -m pytest --junitxml results.xml tests/'
+                        }
+                    }
+                    post {
+                        always {
+                            junit allowEmptyResults: true, testResults: 'results.xml'
+                        }
+                    }
+                }
+            }
+        }
         stage('Snyk Scan Python Image') {
             steps {
                 withCredentials([string(credentialsId: 'snyk-token', variable: 'SNYK_TOKEN')]) {
@@ -63,7 +117,6 @@ pipeline {
                 }
             }
         }
-
         stage('Snyk Scan Nginx Image') {
             steps {
                 withCredentials([string(credentialsId: 'snyk-token', variable: 'SNYK_TOKEN')]) {
@@ -76,19 +129,16 @@ pipeline {
                 }
             }
         }
-
         stage('Deploy Containers') {
             steps {
                 script {
                     def dockerComposeContent = """
                     version: '3.8'
-
                     services:
                       python_app:
                         image: exaclly/$PYTHON_IMG_NAME
                         ports:
                           - "8000:8000"
-
                       nginx:
                         image: exaclly/$NGINX_IMG_NAME
                         ports:
@@ -101,36 +151,27 @@ pipeline {
             }
         }
     }
-
     post {
         always {
             script {
-                // Log the start of the cleanup process
                 echo 'Starting cleanup process...'
-
-                // Remove the built Docker images from the disk
                 try {
                     sh '''
-                        echo "Removing Docker image: exaclly/$PYTHON_IMG_NAME"
-                        docker rmi exaclly/$PYTHON_IMG_NAME || echo "Image exaclly/$PYTHON_IMG_NAME already removed or not found."
+                        echo "Removing Docker image: exaclly/${PYTHON_IMG_NAME}"
+                        docker rmi exaclly/${PYTHON_IMG_NAME} || echo "Image exaclly/${PYTHON_IMG_NAME} already removed or not found."
                     '''
                 } catch (Exception e) {
-                    echo "Error during Docker image removal: ${e.getMessage()}"
+                    echo "Error during Docker image removal of ${PYTHON_IMG_NAME}: ${e}"
                 }
-
                 try {
                     sh '''
-                        echo "Removing Docker image: exaclly/$NGINX_IMG_NAME"
-                        docker rmi exaclly/$NGINX_IMG_NAME || echo "Image exaclly/$NGINX_IMG_NAME already removed or not found."
+                        echo "Removing Docker image: exaclly/${NGINX_IMG_NAME}"
+                        docker rmi exaclly/${NGINX_IMG_NAME} || echo "Image exaclly/${NGINX_IMG_NAME} already removed or not found."
                     '''
                 } catch (Exception e) {
-                    echo "Error during Docker image removal: ${e.getMessage()}"
+                    echo "Error during Docker image removal of ${NGINX_IMG_NAME}: ${e}"
                 }
-
-                // Clean the workspace
                 cleanWs()
-
-                // Log the end of the cleanup process
                 echo 'Cleanup process completed.'
             }
         }
