fixing java

diff --git a/build2.jenkinsfile b/build2.jenkinsfile
--- a/build2.jenkinsfile
+++ b/build2.jenkinsfile
@@ -2,7 +2,7 @@ pipeline {
     agent {
         docker {
             image 'exaclly/jenkins-agent:latest'
-            args '--user root -v /var/run/docker.sock:/var/run/docker.sock -v /custom/jenkins/workspace:/home/jenkins/agent/workspace -w /home/jenkins/agent/workspace'
+            args '--user root -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/jenkins:/home/jenkins/agent/workspace -w /home/jenkins/agent/workspace'
         }
     }
 
@@ -41,23 +41,21 @@ pipeline {
 
     post {
         always {
-            node('') { // Specify the label for the node
-                script {
-                    echo 'Starting cleanup process...'
-                    try {
-                        sh '''
-                            echo "Removing Docker image: exaclly/$JENKINS_IMG_NAME"
-                            docker rmi exaclly/$JENKINS_IMG_NAME || echo "Image exaclly/$JENKINS_IMG_NAME already removed or not found."
-                        '''
-                    } catch (Exception e) {
-                        echo "Error during Docker image removal: ${e.getMessage()}"
-                    }
-
-                    // Clean workspace using cleanWs step
-                    cleanWs()
-
-                    echo 'Cleanup process completed.'
+            script {
+                echo 'Starting cleanup process...'
+                try {
+                    sh '''
+                        echo "Removing Docker image: exaclly/$JENKINS_IMG_NAME"
+                        docker rmi exaclly/$JENKINS_IMG_NAME || echo "Image exaclly/$JENKINS_IMG_NAME already removed or not found."
+                    '''
+                } catch (Exception e) {
+                    echo "Error during Docker image removal: ${e.getMessage()}"
                 }
+
+                // Clean workspace using cleanWs step
+                cleanWs()
+
+                echo 'Cleanup process completed.'
             }
         }
     }
